export const Icons = {
    // Splash: require("../assets/images/Splash.png"),
    dashboard: require("../assets/images/dashboard.png"),
    internet: require("../assets/images/internet.png"),
    menu: require("../assets/images/menu.png"),
    home: require("../assets/images/home.png"),
    left:require('../assets/images/arrow-left.png'),
    right:require('../assets/images/right-arrows.png'),
    picture1:require('../assets/images/Invoice-bro.png'),
    picture2:require('../assets/images/Spreadsheets-rafiki.png'),
    picture3:require('../assets/images/Onboarding-rafiki.png'),
    picture4:require('../assets/images/Collecting-rafiki.png'),
    refresh:require('../assets/images/refresh.png'),
    rupee:require('../assets/images/rupee.png'),
    bell:require('../assets/images/bell.png'),
    accounting:require('../assets/images/accounting.png'),
    trolley:require('../assets/images/trolley.png'),
    food:require('../assets/images/food.png'),
    stock:require('../assets/images/warehouse.png'),
    supplier:require('../assets/images/inventory.png'),
    customers:require('../assets/images/people.png'),
    order:require('../assets/images/package.png'),
    copy:require('../assets/images/copy.png'),
     share:require('../assets/images/share.png'),
     skip:require('../assets/images/skip.png'),
    //  purchage:require('../assets/images/purchase.png'),
     down:require('../assets/images/down-arrow.png'),
     tax:require('../assets/images/tax.png'),
     user:require('../assets/images/user.png'),
     back:require('../assets/images/arrow.png'),
    photo:require('../assets/images/photo.png'),
    current:require('../assets/images/target.png'),
    demo:require('../assets/images/demo.jpg'),
    business:require('../assets/images/business.jpg'),
    plus:require('../assets/images/add.png'),
    gift:require('../assets/images/giftbox.png'),
    money:require('../assets/images/Money.png'),
    coin:require('../assets/images/Coins.png'),
    product:require('../assets/images/paper.png'),
    download:require('../assets/images/downloads.png'),
    qr:require('../assets/images/qr.png'), 
    search:require('../assets/images/search.png'),
    check:require('../assets/images/check.png'),
    delete:require('../assets/images/delete.png'),
    premium:require('../assets/images/premium.png'),
    premium1:require('../assets/images/premium1.png'),
    crown:require('../assets/images/crown.png'),
    diamond:require('../assets/images/diamond.png'),
    baner:require('../assets/images/banner6.jpg'),
    dots:require('../assets/images/dots.png'),
    item1:require('../assets/images/item1.jpeg'),
    item2:require('../assets/images/item2.jpeg'),
    item3:require('../assets/images/item3.jpeg'),
    leftArrow: require('../assets/images/leftArrow.png'),
   edit: require('../assets/images/edit.png'),
   groceries: require('../assets/images/groceries.png'),
   calender:require('../assets/images/Calender.png'),
   };


export const Fonts = {
    Poppins_Black: "Poppins-Black",
    Poppins_BlackItalic: "Poppins-BlackItalic",
    Poppins_Bold: "Poppins-Bold",
    Poppins_BoldItalic: "Poppins-BoldItalic",
    Poppins_ExtraBold: "Poppins-ExtraBold",
    Poppins_ExtraBoldItalic: "Poppins-ExtraBoldItalic",
    Poppins_ExtraLight: "Poppins-ExtraLight",
    Poppins_ExtraLightItalic: "Poppins-ExtraLightItalic",
    Poppins_Italic: "Poppins-Italic",
    Poppins_Light: "Poppins-Light",
    Poppins_LightItalic: "Poppins-LightItalic",
    Poppins_Medium: "Poppins-Medium",
    Poppins_MediumItalic: "Poppins-MediumItalic",
    Poppins_Regular: "Poppins-Regular",
    Poppins_SemiBold: "Poppins-SemiBold",
    Poppins_SemiBoldItalic: "Poppins-SemiBoldItalic",
    Poppins_Thin: "Poppins-Thin",
    Poppins_ThinItalic: "Poppins-ThinItalic",
  };